Migrate paper changes to whitepaper
uptane/papers pull request #10
Opened 2022-07-06 18:51 UTC by adityasaky

2022-07-06 18:52 UTC, adityasaky commented
This is still a work in progress with more changes coming soon, but the stuff here should be good for review.

2022-07-07 16:13 UTC, jhdalek55 requested changes
see two small fixes in text

2022-07-07 16:13 UTC, jhdalek55 commented on scudo-whitepaper.md
>  If there is any upside to this, it is that no one is ignoring supply chain issues anymore.  In the spring of 2021, President Joseph R. Biden issued a number of Executive Orders related to supply chai
In the spring of 2021, President Joseph R. Biden issued a number of Executive Orders related to supply chains in the wake of SolarWinds and other hacks.

In the edits we lost the reference to the "this" in "...this and other hacks"

2022-07-07 16:13 UTC, jhdalek55 commented on scudo-whitepaper.md
> +Any recommended actions, however, particularly anything mandated by the Federal government, should carefully consider the diverse industries such rules will affect. Solutions must work in a variety o
Remove the repeated word "party" in the 14th line ("...an extreme example of the risks inherent in the use of third-party..." Take out the word "party" that follows.

2022-07-07 16:14 UTC, jhdalek55 approved these changes

2022-07-07 16:41 UTC, jhdalek55 approved these changes

2022-07-07 16:55 UTC, jhdalek55 requested changes

2022-07-07 16:55 UTC, jhdalek55 commented on scudo-whitepaper.md
> +Performing full in-toto verification can be a resource intensive process for some vehicle ECUs, such as those designated as partial verification ECUs in Uptane. In these situations, other ECUs capabl
Minor capitalizations for consistency...Primary ECU ...full verification Secondary, etc.

2022-07-07 16:55 UTC, jhdalek55 commented on scudo-whitepaper.md
> +For vehicles with no ECUs capable of performing in-toto verification, as a stopgap measure, the Image repository may perform in-toto verification to generate a new “summary link” metadata file. The l
Move "as a stopgap measure" to the front of the first sentence --- "As a stopgap measure for vehicles with no ECUs capable of performing in-toto verification, the Image repository may..." Also again Primary ECU

2022-07-07 16:55 UTC, jhdalek55 commented on scudo-whitepaper.md
>  Scudo can clearly combine the state of the art in software update security and software supply chain security systems. However, as with any framework that relies on user-defined policies, Scudo also
Add the word "only" to the last sentence  i.e. "allowing each part of the software supply chain only as much..."

2022-07-07 20:27 UTC, adityasaky commented on scudo-whitepaper.md
>  If there is any upside to this, it is that no one is ignoring supply chain issues anymore.  In the spring of 2021, President Joseph R. Biden issued a number of Executive Orders related to supply chai
Added reference to Sunburst in the previous line, upside to... because we'd have the same issue there otherwise.

2022-07-07 20:32 UTC, adityasaky commented
Resolved your comments I believe, @jhdalek55!

2022-07-07 20:52 UTC, jhdalek55 approved these changes

2022-07-07 20:52 UTC, jhdalek55 commented
Ok. These are good to go as far as I'm concerned.

2022-07-08 19:03 UTC, adityasaky commented
cc @mnm678

2022-07-12 23:31 UTC, mnm678 approved these changes

2022-07-12 23:32 UTC, mnm678 commented
> cc @mnm678 Do we publish an updated version of this and the PDF?

Yes, this looks good to me

2022-07-13 18:52 UTC, adityasaky commented
I don't have merge powers on this repo. I think we can go ahead though. :)

2022-07-13 18:53 UTC, merged

2022-07-13 18:53 UTC, jhdalek55 commented
Done. Thanks.